# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-14 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='end_at',
            new_name='ends_at',
        ),
    ]
