# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20191114_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='ends_at',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='start_at',
            field=models.TimeField(null=True),
        ),
    ]
