# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-15 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_auto_20191115_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='suspend',
            new_name='autostart',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='resource_on',
        ),
    ]
