# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-15 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_auto_20191115_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='duration_threshold',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='proxy',
            name='is_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='last_access_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='scale_resource_type',
            field=models.CharField(choices=[('deployment', 'deployment'), ('stateful_set', 'statefulset'), ('rs', 'replica_set')], max_length=255),
        ),
    ]
