# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-16 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_auto_20191115_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='replicas',
            field=models.IntegerField(default=1),
        ),
    ]
