# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0006_proxy_replicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='service_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='service_port',
            field=models.IntegerField(null=True),
        ),
    ]
